---
# This Playbook sets up a Vagrant Fedora 28 VM
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Update all Packages
    dnf:
      name: '*'
      state: latest

  - name: Install OpenShift Development Tools
    dnf:
      state: present
      name:
        - git
        - skopeo
        - cri-o
        - cri-tools
        - buildah
        - podman
        - libselinux-python
        - vim
        - golang
        - python
        - python-devel
        - python3
        - python3-devel
        - dnf-plugins-core

  - name: Enable Docker-CE
    command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker-CE
    dnf:
      state: present
      name:
      - docker-ce

  - name: Add user vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: True

  - name: Install OpenShift Origin Client
    unarchive:
      creates: /usr/local/bin/oc
      src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
      remote_src: yes
      dest: /usr/local/bin
      mode: 0755
      owner: root
      group: root
      extra_opts:
        - --strip=1

  - name: Install jq
    get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      dest: /usr/local/bin/jq
      mode: 0755

  - name: Install S2I
    unarchive:
      creates: /usr/local/bin/s2i
      src: https://github.com/openshift/source-to-image/releases/download/v1.1.12/source-to-image-v1.1.12-2a783420-linux-amd64.tar.gz
      remote_src: yes
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
      extra_opts:
        - --strip=1

  - name: Install Terraform
    unarchive:
      creates: /usr/local/bin/terraform
      src: https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      remote_src: yes
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
#      extra_opts:
#        - --strip=1

  - name: Install bash-git-prompt
    git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: "{{ item }}/.bash-git-prompt"
      clone: yes
    with_items:
    - "/root"
    - "/home/vagrant"
    tags:
    - install_bash_customization

  - name: Change ownership of bash-git-prompt
    file:
      path: "{{ item.directory }}/.bash-git-prompt"
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
      recurse: yes
    with_items:
    - { directory: "/root",         user: "root",     group: "root" }
    - { directory: "/home/vagrant", user: "vagrant", group: "vagrant" }
    tags:
    - install_bash_customization

  - name: Install .bashrc
    copy:
      src: ../files/bashrc
      dest: "{{ item.directory }}/.bashrc"
      mode: 0644
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
    with_items:
    - { directory: "/root",         user: "root",     group: "root" }
    - { directory: "/home/vagrant", user: "vagrant", group: "vagrant" }
    tags:
    - install_bash_customization

  - name: Install .bash_profile
    copy:
      src: ../files/bash_profile
      dest: "{{ item.directory }}/.bash_profile"
      mode: 0644
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
    with_items:
    - { directory: "/root",         user: "root",     group: "root" }
    - { directory: "/home/vagrant", user: "vagrant", group: "vagrant" }
    tags:
    - install_bash_customization

  - name: Create /etc/containers/registries.conf
    copy:
      src: ./files/registries.conf
      dest: /etc/containers/registries.conf
      owner: root
      group: root
      mode: 0644

  - name: Enable and start Docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install VirtualEnv
    pip:
      state: present
      name:
      - virtualenv

  - name: Copy pip requirements file
    copy:
      src: ./files/requirements.txt
      dest: /tmp/requirements.txt
      owner: vagrant
      group: vagrant
      mode: 0664

  - name: Install Python Packages into VirtualEnv
    become: False
    pip:
      requirements: /tmp/requirements.txt
      virtualenv: /home/vagrant/ve_home
      virtualenv_python: python2.7
#      virtualenv_python: python3.6

  - name: Download Go Dep
    get_url:
      url: https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
      dest: /usr/local/bin/dep
      mode: 0755
      owner: root
      group: root

  - name: Setup GOPATH
    file:
      path: /home/vagrant/gopath
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: Install Operator Framework
    become: false
    git:
      repo: https://github.com/operator-framework/operator-sdk
      dest: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
      clone: yes

  - name: Build Operator SDK
    become: false
    command: make dep
    args:
      chdir: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
    environment:
      GOPATH: /home/vagrant/gopath

  - name: Install Operator SDK
    become: false
    command: make install
    args:
      chdir: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
    environment:
      GOPATH: /home/vagrant/gopath
