---
# This Playbook sets up a Vagrant Fedora 28 VM
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Update all Packages
    dnf:
      name: '*'
      state: latest

  - name: Install OpenShift Development Tools
    dnf:
      state: present
      name:
        - git
        - skopeo
        - buildah
        - maven
        - java-1.8.0-openjdk-devel
        - ansible
        - podman
        - libselinux-python
        - cri-o
        - cri-tools
        - vim
        - golang
        - python-devel
        - dnf-plugins-core

  - name: Enable Docker-CE
    command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker-CE
    dnf:
      state: present
      name:
      - docker-ce

  - name: Add user vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: True

  - name: Downloaded OpenShift Origin Client
    unarchive:
      src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
      remote_src: yes
      dest: /usr/local/bin
      mode: 0755
      owner: root
      group: root
      extra_opts:
        - --strip=1

  - name: Download jq-linux64 1.5
    ignore_errors: true
    get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      dest: /usr/local/bin/jq
      mode: 0755

  - name: Install S2I Executable
    unarchive:
      src: https://github.com/openshift/source-to-image/releases/download/v1.1.12/source-to-image-v1.1.12-2a783420-linux-amd64.tar.gz
      remote_src: yes
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
      extra_opts:
        - --strip=1

  - name: Install OpenWhisk CLI (wsk)
    unarchive:
      src: https://github.com/projectodd/openwhisk-openshift/releases/download/latest/OpenWhisk_CLI-latest-linux-amd64.tgz
      remote_src: yes
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755

  - name: Install bash-git-prompt for root
    git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: /root/.bash-git-prompt
      clone: yes

  - name: Install bash-git-prompt for vagrant
    git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: /home/vagrant/.bash-git-prompt
      clone: yes

  - name: Change ownership of bash-git-prompt to vagrant
    file:
      path: /home/vagrant/.bash-git-prompt
      owner: vagrant
      group: vagrant
      recurse: yes

  - name: Install .bashrc for root
    copy:
      src: ./files/bashrc
      dest: /root/.bashrc
      mode: 0644
      owner: root
      group: root

  - name: Install .bashrc for vagrant
    copy:
      src: ./files/bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

  - name: Install .bash_profile for root
    copy:
      src: ./files/bash_profile
      dest: /root/.bash_profile
      mode: 0644
      owner: root

  - name: Install .bash_profile for vagrant
    copy:
      src: ./files/bash_profile
      dest: /home/vagrant/.bash_profile
      mode: 0644
      owner: vagrant
      group: vagrant

  - name: Create /etc/containers/registries.conf
    file:
      src: ./files/registries.conf
      dest: /etc/containers/registries.conf
      owner: root
      group: root
      mode: 0644

  - name: Enable and start Docker
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Install VirtualEnv
    pip:
      state: present
      name:
      - virtualenv

  - name: Copy setup_ve script
    copy:
      src: ./files/setup_ve
      dest: /usr/local/bin/setup_ve
      owner: root
      group: root
      mode: 0755

  - name: Create Virtual Environment Top level Directory
    file:
      path: /home/vagrant/ve_home
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: Create Virtual Environment
    command: /usr/local/bin/setup_ve /home/vagrant/ve_home

  - name: Download Go Dep
    get_url:
      url: https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
      dest: /usr/local/bin/dep
      mode: 0755
      owner: root
      group: root

  - name: Setup GOPATH
    file:
      path: /home/vagrant/gopath
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0755

  - name: Install Operator Framework
    become: false
    git:
      repo: https://github.com/operator-framework/operator-sdk
      dest: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
      clone: yes

  - name: Build Operator SDK
    become: false
    command: make dep
    args:
      chdir: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
    environment:
      GOPATH: /home/vagrant/gopath

  - name: Install Operatr SDK
    become: false
    command: make install
    args:
      chdir: /home/vagrant/gopath/src/github.com/operator-framework/operator-sdk
    environment:
      GOPATH: /home/vagrant/gopath

