# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

if [ -f /usr/local/bin/oc ]; then
        oc completion bash >$HOME/.oc_completion.sh
        source $HOME/.oc_completion.sh
fi

# User specific environment and startup programs
GOPATH=$HOME/gopath

PATH=$PATH:$HOME/bin:/usr/local/bin:$GOPATH/bin

export GOPATH
export PATH
